# Generated by Django 2.2.19 on 2021-05-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_detector', '0002_auto_20210414_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='img_path',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='result_img_path',
        ),
        migrations.AddField(
            model_name='detection',
            name='img',
            field=models.ImageField(null=True, upload_to='input'),
        ),
        migrations.AddField(
            model_name='detection',
            name='result_img',
            field=models.ImageField(null=True, upload_to='result'),
        ),
    ]
