# Generated by Django 2.2.19 on 2021-05-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_detector', '0003_auto_20210510_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='result_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
