# Generated by Django 2.2.19 on 2021-05-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_detector', '0004_auto_20210510_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='input'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='result_img',
            field=models.ImageField(blank=True, null=True, upload_to='result'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='result_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
