# Generated by Django 2.2.19 on 2021-05-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_detector', '0005_auto_20210510_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
